---
- name: Update packages
  ansible.builtin.apt:
    update_cache: true

- name: Upgrade packages
  ansible.builtin.apt:
    name: "*"
    state: latest

- name: Install utilities
  ansible.builtin.apt:
    pkg:
      - net-tools
      - htop
      - ntp
      - man
    install-recommends: false

- name: Install ssh server
  ansible.builtin.apt:
    name: openssh-server
    state: latest

- name: Replace motd banner
  ansible.builtin.template:
    src: /templates/banner.j2
    dest: /etc/motd
    owner: root
    group: root

- name: Replace issue banner
  ansible.builtin.template:
    src: ../templates/banner.j2
    dest: /etc/issue.net
    owner: root
    group: root

- name: Configuring ssh server
  ansible.builtin.copy:
    src: sshd_config
    dest: /etc/ssh/sshd_config
    owner: root
    group: root

- name: Restart ssh server
  ansible.builtin.service: 
    name: sshd
    state: restarted

- name: Configure ntp
  ansible.builtin.template:
    src: ../templates/ntp.conf.j2
    dest: /etc/ntp.conf
    owner: root
    group: root
    
- name: Enable ntp
  ansible.builtin.service:
    name: ntp
    state: started
    enabled: true
